name: Build Legacy AhMyth APK

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04  # 使用老版本Runner确保兼容性

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 使用旧版checkout

      # 设置JDK 8（项目需要旧版Java）
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'  # 使用Zulu JDK确保稳定性

      # 手动安装Android SDK 29（兼容旧项目）
      - name: Install Android SDK
        run: |
          mkdir -p ~/android-sdk
          cd ~/android-sdk
          wget -q https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
          unzip -q sdk-tools-linux-*.zip
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/tools/bin:$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
          yes | $HOME/android-sdk/tools/bin/sdkmanager --install "platform-tools" "platforms;android-29" "build-tools;29.0.3"
          yes | $HOME/android-sdk/tools/bin/sdkmanager --licenses || true

      # 创建必要的local.properties
      - name: Create local.properties
        working-directory: ./AhMyth-Client/android
        run: echo "sdk.dir=$HOME/android-sdk" > local.properties

      # 使用Gradle 4.10.3（适配旧项目）
      - name: Use legacy Gradle
        run: |
          cd ./AhMyth-Client/android
          ./gradlew wrapper --gradle-version 4.10.3

      # 更新为actions/cache@v3（解决弃用警告）
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('​**​/*.gradle*', '​**​/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build APK
        working-directory: ./AhMyth-Client/android
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          ./gradlew assembleRelease

      # 使用actions/upload-artifact@v3
      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: AhMyth-APK
          path: ./AhMyth-Client/android/app/build/outputs/apk/release/*.apk
