name: Build Legacy AhMyth APK

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 升级到 v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4  # 升级到 v4
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Install Android SDK
        run: |
          mkdir -p ~/android-sdk
          cd ~/android-sdk
          wget -q https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
          unzip -q sdk-tools-linux-*.zip
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/tools/bin:$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
          yes | $HOME/android-sdk/tools/bin/sdkmanager --install "platform-tools" "platforms;android-29" "build-tools;29.0.3"
          yes | $HOME/android-sdk/tools/bin/sdkmanager --licenses || true

      - name: Create local.properties
        working-directory: ./AhMyth-Client/android
        run: echo "sdk.dir=$HOME/android-sdk" > local.properties

      - name: Use legacy Gradle
        working-directory: ./AhMyth-Client/android
        run: ./gradlew wrapper --gradle-version 4.10.3

      - name: Cache Gradle
        uses: actions/cache@v4  # 升级到 v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build APK
        working-directory: ./AhMyth-Client/android
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          ./gradlew assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4  # 升级到 v4
        with:
          name: AhMyth-APK
          path: ./AhMyth-Client/android/app/build/outputs/apk/release/*.apk
