name: Build AhMyth APK

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 升级到最新版

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-platform: android-33  # 使用较新的 Android SDK 版本
          sdk-build-tools: 34.0.0
          ndk-version: r25b  # 明确指定 NDK 版本（可选）

      - name: Cache Gradle
        uses: actions/cache@v4  # 升级到 v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('​**​/*.gradle*', '​**​/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission to gradlew
        run: chmod +x ./AhMyth-Client/android/gradlew

      - name: Build APK
        working-directory: ./AhMyth-Client/android
        run: ./gradlew assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4  # 升级到最新版
        with:
          name: AhMyth-APK
          path: ./AhMyth-Client/android/app/build/outputs/apk/release/*.apk
