name: Build AhMyth-Client

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置 Java 环境（AhMyth 需要 OpenJDK 8 或 11）
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      # 3. 设置 Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: '13.0' # 最新的命令行工具版本
          accept-sdk-licenses: true

      # 4. 安装 apktool
      - name: Install apktool
        run: |
          wget https://github.com/iBotPeaches/Apktool/releases/download/v2.8.1/apktool_2.8.1.jar -O apktool.jar
          sudo mv apktool.jar /usr/local/bin/apktool.jar
          sudo chmod +x /usr/local/bin/apktool.jar
          echo "alias apktool='java -jar /usr/local/bin/apktool.jar'" >> ~/.bashrc
          source ~/.bashrc

      # 5. 编译 AhMyth-Client
      - name: Build AhMyth-Client
        working-directory: AhMyth-Client
        run: |
          # 使用 apktool 构建 APK（假设 Smali 文件已准备好）
          apktool b . -o ../Output/ahmyth-client.apk
          # 检查 APK 是否生成
          ls -lh ../Output

      # 6. 签名 APK（可选，AhMyth 需要签名 APK）
      - name: Sign APK
        run: |
          # 生成调试密钥（仅用于测试）
          keytool -genkey -v -keystore debug.keystore -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=Android Debug,O=Android,C=US"
          # 使用 jarsigner 签名 APK
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore debug.keystore Output/ahmyth-client.apk androiddebugkey -storepass android -keypass android
          # 使用 zipalign 优化 APK
          zipalign -v 4 Output/ahmyth-client.apk Output/ahmyth-client-signed.apk

      # 7. 上传构建结果
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ahmyth-client-apk
          path: Output/ahmyth-client-signed.apk
